schema_version: 1

context:
  version: "10.6.1"

package:
  name: cms-combine
  version: ${{ version }}

source:
  url: https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 55f2101381166845d31b2224ed76bc4d3ff603e611d62acd78f6f99528f1b89a
  target_directory: HiggsAnalysis/CombinedLimit

build:
  number: 0
  skip: win

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - root_base
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - root_base
    - libboost-devel
    - eigen
    - vdt
  run:
    - python
    - pandas
    - six
    - gsl

tests:
  - python:
      imports:
        - HiggsAnalysis.CombinedLimit.PhysicsModel
  - files:
      source:
        - HiggsAnalysis/CombinedLimit/data/tutorials/multiDim/
        - HiggsAnalysis/CombinedLimit/data/tutorials/CAT23001/
    script:
      - combine -h
      - text2workspace.py -h

about:
  summary: A software tool used for statistical analysis within the CMS experiment
  description: |
    Combine is a RooStats / RooFit - based software tool used for statistical analysis within the
    CMS experiment. Note that while this tool was originally developed in the Higgs PAG, its usage
    is now widespread within CMS. Combine provides a command-line interface to many different statistical
    techniques, available inside RooFit/RooStats, that are used widely inside CMS.
  license: Apache-2.0
  license_file: HiggsAnalysis/CombinedLimit/LICENSE
  homepage: https://cms-analysis.github.io/HiggsAnalysis-CombinedLimit/
  repository: https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit
  documentation: https://cms-analysis.github.io/HiggsAnalysis-CombinedLimit/

extra:
  recipe-maintainers:
    - nsmith-
    - anigamova
    - kcormi
